# Site settings
title: Uday Shankar's Webpage
author: Uday Shankar
author_avatar: https://gravatar.com/avatar/ad516503a11cd5ca435acc9bb6523536?s=50
email: us@cmu.edu
description: Yet to be decided.
baseurl: "" # optional
#twitter_username: foo_bar
#github_username: foo_bar
github_repo: c-er/c-er.github.io
#google_analytics: UA-80085-YOUR-ID
# disqus: disqus-id

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap